export const SET_REQUESTER_NAME = "SET_REQUESTER_NAME";
export const SET_CUSTOM_FIELD_NAME = "SET_CUSTOM_FIELD_NAME";
export const SET_BOOKMARKED_USERS = "SET_BOOKMARKED_USERS";
export const SET_USER_BOOKMARK_STATUS = "SET_USER_BOOKMARK_STATUS";
export const SET_TOPBAR_GUID = "SET_TOPBAR_GUID";